name: Deploy to App Service

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/DemoApi

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: dotnet publish
        run: dotnet publish -c Release -o publish/DemoApi

      - name: Deploy to App Service slot
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ secrets.APP_NAME }} 
          slot-name: staging
          publish-profile: ${{ secrets.STAGING_PUBLISH_PROFILE  }}
          package: ./src/DemoApi/publish/DemoApi
