name: 01 - Initial deployment

on:
  workflow_dispatch:

jobs:
  provision-resources:
    uses: ./.github/workflows/terraform-provision.yml
    secrets: inherit
  deploy-blue-app-to-production:
    needs: provision-resources
    uses: ./.github/workflows/app-service-deploy.yml
    with:
      ref: blue
    secrets: inherit
  deploy-green-app-to-staging:
    needs: provision-resources
    uses: ./.github/workflows/app-service-deploy.yml
    with:
      slot: staging
      ref: green
    secrets: inherit
