name: 01 - Initial deployment

on:
  workflow_dispatch:

jobs:
  provision-resources:
    uses: ./.github/workflows/terraform-provision.yml
    secrets: inherit
  deploy-blue-app-to-production:
    needs: provision-resources
    uses: ./.github/workflows/app-service-deploy.yml
    with:
      apsName: ${{ needs.provision-resources.outputs.apsName }}
      ref: blue
      publishProfile: ${{ secrets.PRODUCTION_PUBLISH_PROFILE }}
    secrets: inherit
  deploy-green-app-to-staging:
    needs: provision-resources
    uses: ./.github/workflows/app-service-deploy.yml
    with:
      apsName: ${{ needs.provision-resources.outputs.apsName }}
      slot: staging
      ref: green
      publishProfile: ${{ secrets.STAGING_PUBLISH_PROFILE }}
    secrets: inherit
