name: Provision Azure resources with Terraform

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: infra

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set-up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Update GitHub secrets
        run: |
          rgName=$(terraform output -raw resource_group_name)
          apsName=$(terraform output -raw app_service_name)
          gh secret set APP_NAME --body $apsName
          publishProfile=$(az webapp deployment list-publishing-profiles -g $rgName -n $apsName --slot staging --xml)
          gh secret set STAGING_PUBLISH_PROFILE --body $publishProfile
